"""change usr id

Revision ID: 162a2882847f
Revises: 
Create Date: 2020-11-20 19:13:58.154133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '162a2882847f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipe', type_='foreignkey')
    op.create_foreign_key(None, 'recipe', 'user', ['user_id'], ['public_id'])
    op.create_unique_constraint(None, 'user', ['public_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'recipe', type_='foreignkey')
    op.create_foreign_key(None, 'recipe', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
