"""initial migration

Revision ID: b4d5e13f4fab
Revises: 
Create Date: 2021-01-06 14:21:06.839746

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'b4d5e13f4fab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('public_id', sa.String(length=50), nullable=True),
                    sa.Column('username', sa.String(length=64), nullable=True),
                    sa.Column('email', sa.String(length=120), nullable=True),
                    sa.Column('password', sa.String(length=128), nullable=True),
                    sa.Column('avatar', sa.BLOB(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('public_id')
                    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('recipe',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(length=140), nullable=True),
                    sa.Column('slug', sa.String(length=140), nullable=True),
                    sa.Column('body', sa.Text(), nullable=True),
                    sa.Column('time_stamp', sa.DateTime(), nullable=True),
                    sa.Column('user_id', sa.String(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['user.public_id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_recipe_time_stamp'), 'recipe', ['time_stamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recipe_time_stamp'), table_name='recipe')
    op.drop_table('recipe')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
